import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React, { Suspense } from 'react';
import HeaderComponent from '@/components/header';
import SidebarComponent from '@/components/side-bar';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
        <StoreProvider>
          <body className={inter.className}>
            <div className="flex">
              <SidebarComponent />
              <div className="flex-1 min-h-screen">
                <HeaderComponent />
                {children}
              </div>
            </div>
          </body>
        </StoreProvider>
      </Suspense>
    </html>
  );
}
